### ISSUE TITLE
Cannot find module '@zerodep/is-object' or its corresponding type declarations (TS2307)

### ISSUE THREAD

**Issue by moltar** [cdepage/zerodep#14]
Started getting this when upgraded [2.0.7 -> 2.0.10](https://renovatebot.com/diffs/npm/@zerodep%2fis-object/2.0.7/2.0.10).

- CJS
- Node: 18.19.0
- typescript: 5.5.3

---

![screenshot-20240723T091320-WmEjVMiW@2x](https://github.com/user-attachments/assets/1bd93f93-7c16-4b65-9e91-052d50a7a47f)

---

Any ideas?

**Comment by cdepage** [comment]
Hey @moltar , 

Whoa - looks like the source code of the project instead of the compiled and minified version of the code for CJS and ESM targets. 

I've updated the `@zerpdep/is-object` package to v2.0.11 (and verified the right code is on npm).

Apologies for the inconvenience this caused you, thanks for letting me know of the issue - greatly appreciated.

My follow-ups:
- check and fix any other affected packages (suspicion is there are multiple)
- find and fix the bug that's uploading from the  `/src` directory instead of `/dist` directory

**Comment by cdepage** [comment]
- [done] investigate which other packages were affected by this change
- [done] patch-bump all packages in monorepo to trigger a rebuild & redeploy
- [done] remove offending automation that doesn't know a `src` folder from ` dist` folder

Thanks again @moltar

**Comment by moltar** [comment]
Thank you!
